<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login or passcode wrong' => 'Неправильный логин или пароль',
    'Your profile is not activated' => 'Ваш профиль не активирован.',
    'You input wrong email address' => 'Вы вводите неправильный адрес электронной почты',
    'On your email sent passcode' => 'На ваш адрес электронной почты отправлен пароль.',
    'Forgot Password' => 'Забыли пароль?',
    'Login' => 'Вход',
    'Send' => 'Отправить',
    'Registration' => 'Регистрация',
    'You have successfully passed the registration, a letter has been sent to your mail for confirmation.' => 'Вы успешно прошли регистрацию, письмо было отправлено на ваше письмо для подтверждения.',
    'You have successfully confirmed your email.' => 'Вы успешно подтвердили свою электронную почту.',
    'You have successfully confirmed that this mail is not your.' => 'Вы успешно подтвердили, что это почта не является вашим.',
    'You have successfully updated your password.' => 'Вы успешно обновили свой пароль',
    'You have successfully deleted the password link.' => 'Вы успешно удалили ссылку на пароль.',
    'Username (Login)' => 'Логин',
    'Name' => 'Имя',
    'Passcode Old' => 'Текущий пароль',
    'Passcode' => 'Пароль',
    'Passcode repeat' => 'Пароль (повторно)',
    'Email' => 'Электронная почта',
    'Phone' => 'Номер телефона',
    'Captcha' => 'Каптча',
    'User is blocked' => 'Пользователь заблокирован',
    'Registration' => 'Регистрация',
    'Update your account' => 'Обновление учётный записи',
    'Update' => 'Изменить',
    'Update passcode' => 'Изменить пароль',
    'Passcode is updated' => 'Пароль обновлён',
    'Passcode is wrong' => 'Пароль не правильная',
    'User is updated' => 'Пользаватель обновлён',
    'Profile' => 'Пользаватель',
    'Search Text' => 'Поиск...',
    'Search Users' => 'Поиск',
    'Search' => 'Поиск',
    'Status' => 'Статус',
    'Add Date' => 'Дата добавление',
    'Actions' => 'Действие',
    'Is Online' => 'Сейчас на сайте',
    'Online' => 'На сайте',
    'Verified' => 'Подтвержден',
    'Not verified' => 'Не подтвержден',
    'Blocked' => ' Заблокирован',
    'Seconds' => ' Секунд',
    'Minutes' => ' Минут',
    'Hours' => ' Часов',
    'Days' => ' Дней',
    'Profile' => 'Профиль',
    'Logout' => 'Выход',
    'Are you sure?' => 'Уверены?',
];
