<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login or passcode wrong' => 'Login or passcode wrong',
    'Your profile is not activated' => 'Your profile is not activated',
    'You input wrong email address' => 'You input wrong email address',
    'On your email sent passcode' => 'On your email sent passcode',
    'Forgot Password' => 'Forgot Password',
    'Login' => 'Login',
    'Send' => 'Send',
    'Registration' => 'Registration',
    'You have successfully passed the registration, a letter has been sent to your mail for confirmation.' => 'You have successfully passed the registration, a letter has been sent to your mail for confirmation.',
    'You have successfully confirmed your email.' => 'You have successfully confirmed your email.',
    'You have successfully confirmed that this mail is not your.' => 'You have successfully confirmed that this mail is not your.',
    'You have successfully updated your password.' => 'You have successfully updated your password.',
    'You have successfully deleted the password link.' => 'You have successfully deleted the password link.',
    'Username (Login)' => 'Login',
    'Name' => 'Name',
    'Passcode Old' => 'Passcode Old',
    'Passcode' => 'Passcode',
    'Passcode repeat' => 'Passcode repeat',
    'Email' => 'Email',
    'Phone' => 'Phone',
    'Captcha' => 'Captcha',
    'User is blocked' => 'User is blocked',
    'Registration' => 'Registration',
    'Update your account' => 'Update your account',
    'Update' => 'Update',
    'Update passcode' => 'Update passcode',
    'Passcode is updated' => 'Passcode is updated',
    'Passcode is wrong' => 'Passcode is wrong',
    'User is updated' => 'User is updated',
    'Profile' => 'Profile',
    'Search Text' => 'Search...',
    'Search Users' => 'Search',
    'Search' => 'Search',
    'Status' => 'Status',
    'Add Date' => 'Add Date',
    'Actions' => 'Actions',
    'Is Online' => 'Is Online?',
    'Online' => 'Online',
    'Verified' => 'Verified',
    'Not verified' => 'Not verified',
    'Blocked' => ' Blocked',
    'Seconds' => ' Seconds',
    'Minutes' => ' Minutes',
    'Hours' => ' Hours',
    'Days' => ' Days',
    'Profile' => 'Profile',
    'Logout' => 'Logout',
    'Are you sure?' => 'Are you sure?',
];
