<?php
namespace jakharbek\user\registration\models;

use \yii\db\ActiveRecord;

class User extends ActiveRecord{

    public $scenario;
    public static function tableName()
    {
        return "user"; // TODO: Change the autogenerated stub
    }
    public function behaviors()
    {
        return [
            [
                'class' => \yii\behaviors\TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['add_date', 'edit_date'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['edit_date'],
                ],
            ],
            [
                'class' => \yii\behaviors\BlameableBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['id'],
                ],
            ]
        ];
    }
    public function rules()
    {
        return [
            [['name', 'login', 'uid','passcode','status'], 'required'],
            [['name', 'login', 'uid','passcode','status'], 'string', 'max' => 255],
        ];
    }
}