<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login or passcode wrong' => 'Login yoki parol (maxfiy kalit) to`g`ri kiritilmagan',
    'Your profile is not activated' => 'Sizning ro`yxatdan o`tgan profilingiz tasdiqlanmagan.',
    'You input wrong email address' => 'To`g`ri bo`lmagan (email) elektron qutini kiritingiz.',
    'On your email sent passcode' => 'Sizning (email) elektron qutingizga (parol) maxfiy ka`lit jonatildi.',
    'Forgot Password' => 'Maxfiy ka`litni (parolni) unutdingizmi?',
    'Login' => 'Kirish',
    'Send' => 'Jonatish',
    'Registration' => 'Ro`yxatdan o`tish',
    'You have successfully passed the registration, a letter has been sent to your mail for confirmation.' => 'Siz muvaffaqiyatli ro`yxatdan o`tdingiz, sizning elekentron qutingizga (emailga) sizni tasdiqlash uchun xat yuborildi.',
    'You have successfully confirmed your email.' => 'Elektron qutingizni (Emailni) muvaffaqiyatli tasdiqladingiz.',
    'You have successfully confirmed that this mail is not your.' => 'Elektron qutingizni (Emailni) muvaffaqiyatli ro`yxatdan o`chirdingiz.',
    'You have successfully updated your password.' => 'Yangi maxfiy ka`litni (parolni) muvaffaqiyatli qo`ladingiz.',
    'You have successfully deleted the password link.' => 'Yangi maxfiy ka`lit qo`llash uchun manzilni muvaffaqiyatli o`chirdingiz.',
    'Username (Login)' => 'Login',
    'Name' => 'Ism',
    'Passcode Old' => 'Eski (Hozirgi) Maxfiy ka`lit (Parol)',
    'Passcode' => 'Maxfiy ka`lit (Parol)',
    'Passcode repeat' => 'Maxfiy ka`lit (Parol) nusxasi',
    'Email' => 'Elekentron quti (email)',
    'Phone' => 'Telefon raqam',
    'Captcha' => 'Suratdagi tekshiruv ka`liti (kodi)',
    'User is blocked' => 'Foydalanuvchi uchun kirish mumkin emas',
    'Registration' => 'Ro`yxatdan o`tish',
    'Update your account' => 'Ro`yxatdan o`tgan ma`lumotlarni yangilash',
    'Update' => 'Yangilash',
    'Update passcode' => 'Maxfiy ka`litni (parolni) yangilash',
    'Passcode is updated' => 'Maxfiy ka`lit yangilandi',
    'Passcode is wrong' => 'Maxfiy ka`lit to`g`ri kiritilmagan',
    'User is updated' => 'Foydalanuvchi ma`lumotlari yangilandi.',
    'Profile' => 'Foydalanuvchi',
    'Search Text' => 'Qidiruv...',
    'Search Users' => 'Qidiruv',
    'Search' => 'Qidiruv',
    'Status' => 'Holati',
    'Add Date' => 'Qo`shilgan sanasi',
    'Actions' => 'Sozlamalar',
    'Is Online' => 'Hozir saytdami?',
    'Online' => 'Aloqa',
    'Verified' => 'Tasdiqlangan',
    'Not verified' => 'Tasdiqlanmagan',
    'Blocked' => ' Yopilgan',
    'Seconds' => ' Soniya',
    'Minutes' => ' Daqiqa',
    'Hours' => ' Soat',
    'Days' => ' Kun',
    'Profile' => 'Profil',
    'Logout' => 'Chiqish',
    'Are you sure?' => 'Tasdiqlaysizmi?',
];
